- README.md
> test change 3

- README.md
> test change 4

- README.md
> test change #7

- package-lock.json
- src/app/accounts/accounts-routing.module.ts
- src/app/accounts/accounts.module.ts
- src/app/flash-cards/flash-cards-routing.module.ts
- src/app/flash-cards/flash-cards.module.ts
> Create base modules for Accounts and Flash Cards

- src/app/app-routing.module.ts
Team3-Amruta-Routing Entry for Assessment and Video Components
> Team3-Amruta-Routing Entry for Assessment and Video Components

- src/app/accounts/accounts.module.ts
- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/material/material.module.ts
Fixed Material Component/Modules
> Updated sign-up component a bit

- src/app/accounts/accounts.module.ts
Updated a accounts module file
> Updated a accounts module file

- src/app/accounts/accounts-routing.module.ts
- src/app/accounts/login/login.component.html
- src/app/app-routing.module.ts
- src/app/app.component.html
- src/app/app.module.ts
Updated routes for login/signup, and updated a bit
> Updated routes for login/signup, and updated a bit

- src/app/accounts/login/login.component.html
- src/app/accounts/login/login.component.scss
Center LogIn component in middle of page (homepage)
> Center LogIn component in middle of page (homepage)

- src/app/articles/article-homepage/article-homepage.component.html
- src/app/articles/article-homepage/article-homepage.component.scss
Added grid layout and selected articles to show
> changed article home page

- src/app/app.component.html
- src/app/assessment/assessment/assessment.component.html
- src/app/assessment/assessment/assessment.component.scss
- src/app/assessment/assessment/assessment.component.ts
- src/app/footer/footer.component.scss
- src/app/navbar/navbar.component.html
- src/app/navbar/navbar.component.scss
1. Adding click animations in assessment
2. removing menu items in header
3. making footer fixed in the bottom
> Assessment Component, Header and footer

- DB/db.json
Adding Assessment and video content in to db.json
> Adding original data

- package-lock.json
- src/app/app-routing.module.ts
- src/app/articles/add-article/add-article.component.html
- src/app/articles/add-article/add-article.component.ts
- src/app/articles/article-homepage/article-homepage.component.html
- src/app/articles/article/article.component.html
- src/app/articles/article/article.component.ts
- src/app/navbar/navbar.component.html
> updated routes for articles

- DB/db.json
- src/app/app-routing.module.ts
- src/app/app.component.html
- src/app/assessment/assessment-form/assessment-form.component.html
- src/app/assessment/assessment-form/assessment-form.component.scss
- src/app/assessment/assessment-form/assessment-form.component.ts
- src/app/assessment/assessment.module.ts
- src/app/assessment/assessment.service.ts
- src/app/assessment/assessment/assessment.component.html
- src/app/assessment/assessment/assessment.component.scss
- src/app/assessment/assessment/assessment.component.ts
1.Creating Navigation from assessment component to specif course component
2. updating some changes in db.json file
> Creating Navigaton from assessment component to specif course component

- src/app/app.component.html
- src/app/assessment/alert/alert.component.html
- src/app/assessment/alert/alert.component.scss
- src/app/assessment/alert/alert.component.spec.ts
- src/app/assessment/alert/alert.component.ts
- src/app/assessment/assessment-form/assessment-form.component.html
- src/app/assessment/assessment-form/assessment-form.component.scss
- src/app/assessment/assessment-form/assessment-form.component.ts
- src/app/assessment/assessment.module.ts
> assessment Validation

- src/app/app-routing.module.ts
- src/app/assessment/assessment.module.ts
- src/app/assessment/assessment/assessment.component.html
- src/app/assessment/assessment/assessment.component.ts
- src/app/assessment/new-assessment/new-assessment.component.html
- src/app/assessment/new-question/new-question.component.html
- src/app/assessment/new-question/new-question.component.scss
- src/app/assessment/new-question/new-question.component.spec.ts
- src/app/assessment/new-question/new-question.component.ts
- src/app/navbar/navbar.component.html
Adding new Question component to assessment component
> Adding new Question component to assessment component

- src/app/navbar/navbar.component.html
> Updated navbar a bit

- src/app/navbar/navbar.component.html
Removing Menu buttons in navBar for assessment component button
> Removing Menu buttons in navBar for assessment component button

- src/app/assessment/assessment-form/assessment-form.component.spec.ts
- src/app/assessment/assessment.service.spec.ts
- src/app/assessment/assessment.service.ts
- src/app/assessment/assessment/assessment.component.spec.ts
- src/app/assessment/new-assessment/new-assessment.component.spec.ts
- src/app/assessment/new-assessment/new-assessment.component.ts
- src/app/assessment/new-question/new-question.component.html
- src/app/assessment/new-question/new-question.component.spec.ts
- src/app/assessment/new-question/new-question.component.ts
UNIT Testing for each component and service
> UNIT Testing

- src/app/assessment/assessment-form/assessment-form.component.html
- src/app/assessment/assessment-form/assessment-form.component.scss
- src/app/assessment/assessment/assessment.component.html
- src/app/assessment/new-assessment/new-assessment.component.html
- src/app/assessment/new-assessment/new-assessment.component.scss
- src/app/assessment/new-question/new-question.component.html
- src/app/assessment/new-question/new-question.component.scss
- src/app/footer/footer.component.scss
Small changes on flicker in assessment component due to footer
> Small changes on flicker in assessment component due to footer

- src/app/assessment/assessment-form/assessment-form.component.html
- src/app/assessment/assessment-form/assessment-form.component.scss
- src/app/assessment/assessment-form/assessment-form.component.spec.ts
- src/app/assessment/assessment-form/assessment-form.component.ts
- src/app/assessment/assessment/assessment.component.html
- src/app/assessment/assessment/assessment.component.scss
- src/app/assessment/assessment/assessment.component.spec.ts
- src/app/assessment/assessment/assessment.component.ts
- src/app/assessment/new-assessment/new-assessment.component.html
- src/app/assessment/new-assessment/new-assessment.component.scss
- src/app/assessment/new-assessment/new-assessment.component.spec.ts
- src/app/assessment/new-assessment/new-assessment.component.ts
- src/app/assessment/new-question/new-question.component.scss
- src/app/assessment/new-question/new-question.component.spec.ts
Majour changes in Assessment module
> Majour changes in Assessment module
